### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by thedrow** [celery/jumpstarter#15]
It's time we start continuously testing this repository to ensure we don't break anything in the future.

- [x] Implement testing matrix using [nox](https://nox.thea.codes/) & [nox-poetry](https://github.com/cjolowicz/nox-poetry)
- [x] Implement continuous integration using Github Actions
- [x] Integrate with codecov for coverage reporting
- [x] Integrate with [deepcode](https://pypi.org/project/deepcode/) for code improvement suggestions

**Comment by ahopkins** [comment]
Why `nox` and not `tox`? Why not try and keep it similar to `celery`?

**Comment by auvipy** [comment]
can github action parse nox files?

**Comment by auvipy** [comment]
> Why `nox` and not `tox`? Why not try and keep it similar to `celery`?

nox provide python file like syntax https://nox.thea.codes/en/stable/tutorial.html :D if this goes well we might consider changing celery too.

**Comment by ahopkins** [comment]
I don't profess to be an expert. I only setup one package on GH actions about a month or two ago. But it seems similar enough to doing GL or Travis where you are defining the container that runs everything in. So, as long as the environment is setup, I see no reason why it couldn't run nox.

**Comment by thedrow** [comment]
`nox` allows us to programmatically introduce network partitions using [blockade](https://github.com/worstcase/blockade) or something like [seaworthy](https://github.com/praekeltfoundation/seaworthy).
[tox-docker](https://github.com/tox-dev/tox-docker) is far less flexible.

**Comment by thedrow** [comment]
@ahopkins If you think tox is what we should be using in the future, now's the time to make the argument for it.

**Comment by ahopkins** [comment]
I am not familiar with blockade or seaworthy. I have used tox-docker with success.

My comment was based upon two things: (1) celery uses tox, and (2) tox is widely known and adopted in the Python community (not really a reason to shirk it). If the idea is to use this as an experiment before switching celery, then go for it. I have no objection.

**Comment by thedrow** [comment]
@ahopkins Very large projects like salt and urllib3 [use nox](https://nox.thea.codes/en/stable/index.html#projects-that-use-nox).
There's no reason not to try it. If it works well, we can replace tox with nox without fear.

**Comment by auvipy** [comment]
just sharing a thing from my little knowledge reading with github action doc so far, even without tox/nox we can run CI/CD in github action using their built-in features as well. [doing that in django-activity-stream & might try in celery projects]
