### ISSUE TITLE
what happend to this repo?

### ISSUE THREAD

**Issue by nitishxp** [celery/jumpstarter#39]
Is this repo still alive?

**Comment by auvipy** [comment]
it is.

**Comment by nitishxp** [comment]
its for celery next gen right? I was afraid that it became a stale repo....

**Comment by auvipy** [comment]
this is just part of that. initial target is async await based celery 6.

**Comment by nitishxp** [comment]
Where i can see the progess since repo is not being updated since month back :)

**Comment by auvipy** [comment]
you should follow celery/celery

**Comment by nitishxp** [comment]
Sounds good thanks for the update
